### ISSUE TITLE
支付错误

### ISSUE THREAD

**Issue by wwangning** [FoneG/FGIAPService#2]
内购沙盒测试的时候 第一次登录账号 然后购买 支付完成后 又弹了一次购买的弹窗  下次购买不用登录账号 就正常了 大佬遇到过吗

**Comment by FoneG** [comment]
没理解，“支付完成后 又弹了一次购买的弹窗” 是说又重新走了一次购买流程？倒是没碰到这种情况

**Comment by wwangning** [comment]
对 点击支付的时候 弹出登录沙盒账号的界面 登录好 接着弹出支付的弹出 输入密码 支付完成后 代理回调(updatedTransactions)方法不走 接着又弹了一次支付弹窗  这次输入完密码支付后 代理回调走了 杀死app 再次点击支付就正常了

**Comment by FoneG** [comment]
用的是FGIAPService吗，我理解是2次支付走的是同一个订单，系统原因重新触发购买流程但不会影响后续支付结果。可以说下手机版本晚点我验证一下

**Comment by xiaohange** [comment]
你好，沙盒环境测试验证二次验证订单一直报错 21003，这个有办法解决吗？

**Comment by FoneG** [comment]
> 你好，沙盒环境测试验证二次验证订单一直报错 21003，这个有办法解决吗？

验签失败问题可以直接抛给后端同学
