### ISSUE TITLE
可能会出现掉单问题

### ISSUE THREAD

**Issue by mb061** [FoneG/FGIAPService#4]
在applicationUsername为空的时候，我看你这边获取tradeNO是根据productIdentifier，在productIdentifier相同的情况下，tradeNO可能会与凭证对应不上，导致服务端验证不通过

**Comment by FoneG** [comment]
一般业务订单只是都跟productIdentifier绑定，所以对服务器来说实际上只care结束的是不是这个类型的订单，而不是关心具体哪一个。  
你们是业务订单的关系是怎么样？

**Comment by mb061** [comment]
我们现在已经不验证订单号了，只验证凭证。按照你的意思是，比如我昨天生成一个6块钱的订单，然后今天我购买个6块钱的订单，用昨天产生的订单号来验证，也是可以验证通过的，是吧？

**Comment by FoneG** [comment]
> 我们现在已经不验证订单号了，只验证凭证。按照你的意思是，比如我昨天生成一个6块钱的订单，然后今天我购买个6块钱的订单，用昨天产生的订单号来验证，也是可以验证通过的，是吧？

是的

**Comment by mb061** [comment]
那我其实感觉这个订单号有点鸡肋啊

**Comment by FoneG** [comment]
> 那我其实感觉这个订单号有点鸡肋啊

业务需要呀，如果没有订单号怎么展示支付订单列表

**Comment by mb061** [comment]
其实也是存在订单号的，只不过我们现在是支付成功去后台验证的时候再去创建订单号
