### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by captainnx** [FoneG/FGIAPService#7]
大佬你好，想请教一下，当用户只有支付宝或者微信的扣款截图的时候，如何去反查receipt的信息呢

**Comment by FoneG** [comment]
内购跟支付宝微信是2个不同的东西，没关联的

**Comment by FoneG** [comment]
> 大佬你好，想请教一下，当用户只有支付宝或者微信的扣款截图的时候，如何去反查receipt的信息呢

内购跟支付宝微信是2个不同的东西，没关联的

**Comment by captainnx** [comment]
明白，但是内购会去支付宝微信请求扣款，无论是apple购买记录里的文稿编号，还是支付宝的流水号，好像都无法跟receipt进行关联，这样好像无法反查到具体某个用户啊

**Comment by FoneG** [comment]
> 明白，但是内购会去支付宝微信请求扣款，无论是apple购买记录里的文稿编号，还是支付宝的流水号，好像都无法跟receipt进行关联，这样好像无法反查到具体某个用户啊

让后端在拿到支付成功的receipt以后跟当前用户信息（一般都是通过订单）进行绑定，并向apple校验是否支付成功。不需要关系用户具体通过什么方式去完成apple的支付

**Comment by FoneG** [comment]
> 明白，但是内购会去支付宝微信请求扣款，无论是apple购买记录里的文稿编号，还是支付宝的流水号，好像都无法跟receipt进行关联，这样好像无法反查到具体某个用户啊

确实没听过通过微信的支付信息直接反查receipt的情况。按照我的理解是商户需要自己维护着用户的订单支付信息，然后再根据用户的截图时间来确定是哪个订单，进而反查receipt信息

**Comment by zhumingke** [comment]
自定订阅的，用户取消订阅，退款，只能通过服务端验证码
